### ISSUE TITLE
Upload 1.1.2 to curseforge

### ISSUE THREAD

**Issue by sqrvrt** [DeadlyMC/ProtoSky#11]

**Comment by LucasJoel1** [comment]
https://www.curseforge.com/minecraft/mc-mods/protosky#c48
That is why it is not on the curseforge page

**Comment by sqrvrt** [comment]
I have seen that page myself, but recently I found that it was closed.
![изображение](https://user-images.githubusercontent.com/75751809/148289890-34f9c2a9-0c88-48e9-b7ff-b46607c4a66f.png)

**Comment by polarbub** [comment]
Curseforge still doesn't like it even though the other project it gone :( 

![Screenshot_20220109_123344](https://user-images.githubusercontent.com/71790726/148695648-8239a465-6501-42d7-ad20-81b16edfaddf.png)

**Comment by polarbub** [comment]
I fixed a bug, lets see if it'll take it now.

**Comment by polarbub** [comment]
it worked, see [https://www.curseforge.com/minecraft/mc-mods/protosky/files/3600120](https://www.curseforge.com/minecraft/mc-mods/protosky/files/3600120)
