### ISSUE TITLE
Option to leave the End unchanged?

### ISSUE THREAD

**Issue by Bishop0702** [DeadlyMC/ProtoSky#14]
Is it possible to add such option?

**Comment by polarbub** [comment]
yes, here it is
[src.zip](https://github.com/DeadlyMC/ProtoSky/files/8149116/src.zip)
[protosky-1.1.4](https://www.mediafire.com/file/pyfvpwfpaw776vh/protosky-1.1.4.jar/file)

**Comment by Bishop0702** [comment]
Works great. Thank you for your help.
