### ISSUE TITLE
Ghost spawn ceiling

### ISSUE THREAD

**Issue by JillStingray1** [DeadlyMC/ProtoSky#18]
Worlds generated using this mod results in a 'ghost ceiling' being created at the height of what the original terrain is at, resulting in the highest spawnable block being significantly higher than the ones in the chunk, as seen in the image.
![bruh](https://user-images.githubusercontent.com/87292700/169805667-c9c40ab8-6f40-4c06-b732-0856b73b90f8.png)

**Comment by polarbub** [comment]
Can you test the 1.17 version of the mod and vanilla 1.18?

**Comment by polarbub** [comment]
Also what am I supposed to be looking at in the screenshot?
The red part is spawn protection
The yellow part is a mineshaft

**Comment by JillStingray1** [comment]
Apologies on not being clear with the screenshot, the block I am at is at y = 89, using spawn test in quickcarpet on this block shows that the highest spawnable block being at 87, despite there clearly being no block at y = 87.

**Comment by JillStingray1** [comment]
This glitch is not present in the latest 1.17 release. Placing a block at a y value above the 'ghost ceiling' and breaking it will set the highest spawnable for the corresponding x and z coordinate back to a valid block..

**Comment by polarbub** [comment]
So when there is no block the highest spawnable block gets set to y0?

**Comment by polarbub** [comment]
I remembered what they're called, they're called hightmaps. I left out the call to update them. Can you try this jar? 
https://cdn.discordapp.com/attachments/816392091009024010/978477105903968256/protosky-1.1.5.jar
https://cdn.discordapp.com/attachments/816392091009024010/978477105711022130/protosky-1.1.5-sources.jar

**Comment by JillStingray1** [comment]
Vanilla behavior is that if there are no blocks in a x-z coordinate , the highest spawnable block would be y = 0, however, in this mod, upon world generation, the highest spawnable block corresponds to the original heightmap of the terrain as if the blocks were there, this causes various problems, such as reducing the spawn rates of farms place below the heightmap, or preventing rain from falling below said heightmap, the invisible heightmap is updated once a block is placed above the invisible height map, removing said block will cause that specific x-z coordinate to return to Vanilla behavior. The given jar doesn't resolve the issue.
![2022-05-24_17 01 33](https://user-images.githubusercontent.com/87292700/169993811-9f4307e8-c35d-4844-9c28-1e04c658f0b4.png)
This picture demonstrates that although it is raining and I am in a biome where it can rain, it is stopped by the invisible heightmap. The single trail of rain is caused by placing a block above the invisible heightmap and then removing the block, which updates the highest block in the coordinate to be at the correct y level.

**Comment by polarbub** [comment]
Can you try this one? It manually sets the block at y255 to structure void and then back to air https://cdn.discordapp.com/attachments/816392091009024010/978835633139220590/protosky-1.1.5-sources.jar 
https://cdn.discordapp.com/attachments/816392091009024010/978835632954675200/protosky-1.1.5.jar

**Comment by JillStingray1** [comment]
The given jar doesn't resolve the issue.

**Comment by polarbub** [comment]
How do you test it? I'd like to test locally

**Comment by JillStingray1** [comment]
Generate a new world using the mod, and set the weather to rain, and then fly down to a low y value, normally the rain will fall down to y=-64, but because of the invisible heightmap, the rain will stop on said heightmap, if the rain is present at y=-64, then the glitch is fixed.

**Comment by polarbub** [comment]
Can you test this one? It works for me and is the fixed version of the above one. https://cdn.discordapp.com/attachments/816392091009024010/980941851525799998/protosky-1.1.5-sources.jar
https://cdn.discordapp.com/attachments/816392091009024010/980941851236384768/protosky-1.1.5.jar

**Comment by JillStingray1** [comment]
This has resolved the issue.

**Comment by polarbub** [comment]
Fixed in v1.1.6
