### ISSUE TITLE
Endportal Frames dont generate (neither do end cities)

### ISSUE THREAD

**Issue by GinTonic34** [DeadlyMC/ProtoSky#20]
If I create a new world in 1.19, End Portals and End cities (the shulkers and the elytra) dont generate. This error is not entirely consistent, as sometimes (very rarely) they do generate. Most of the time they dont. I cant find any correlation between that and i dont know if its my PC or the mod. (Skyblock is the only mod installed)

![image](https://user-images.githubusercontent.com/107366639/173257508-e2f375fc-6267-47aa-9b4c-571fa9192896.png)

**Comment by GinTonic34** [comment]
left is skyblock mod and right is vanilla generation. Same seed, same settings, same position.

**Comment by polarbub** [comment]
Oop

**Comment by polarbub** [comment]
Did the generation change in 1.18 to 1.19?

**Comment by GinTonic34** [comment]
I dont know, I dont think so. because I occationally get the endportal to generate (but I dont know why). I tried a lot of options in generating worlds (like different gamemodes, difficulties, renaming worlds) but I cant reproduce the error consistently. I also dont know if its just on my PC or if it happens to others as well.

**Comment by GinTonic34** [comment]
BTW I do get the advancement (Eye Spy) in the Skyblock mod. So the stronghold is definetly there.

**Comment by GinTonic34** [comment]
Update: As far as I can tell, after I start the fabric launcher the first generated world does come with the portal in place. Any further worlds generated in that session dont have the portals. I have to restart the launcher to get the portal to generate again. However, the end cities never generate, not even on the first world. Thats what I could find with my testing. Maybe others can try and replicate that.

This is the first world generation after restarting the fabric launcher:

![image](https://user-images.githubusercontent.com/107366639/173258958-f8ca767b-6b6c-429b-9a74-a682e5e1b17e.png)

This is the second world generation after restarting the launcher. Same settings, seed, place, everything. Generated right after the first one (picture above) - no portal...

![image](https://user-images.githubusercontent.com/107366639/173259076-ea8cd949-c0c2-4abc-90f4-07b6acad183a.png)

**Comment by polarbub** [comment]
I just checked three on my own world and it works fine

**Comment by polarbub** [comment]
Maybe look around a bit, it might be random

**Comment by GinTonic34** [comment]
Alright, must be on my installation then. Thanks for checking!

**Comment by polarbub** [comment]
The part that I'm changing isn't random. The code it is in https://github.com/DeadlyMC/ProtoSky/blob/master/src/main/java/protosky/stuctures/StrongHoldHelper.java
I haven't checked any end cities yet though.

**Comment by polarbub** [comment]
The first end city I checked is gone, weird

**Comment by GinTonic34** [comment]
(Disclaimer: I dont know nothing about coding/java/modding. So I dont really understand what the code does.)

Can you try the thing I specified above (Generating a world right after restarting the launcher and then right after that regenerating the same world?)

**Comment by polarbub** [comment]
I don't use the minecraft launcher. It's just the dedicated server

**Comment by polarbub** [comment]
I know what was doing the end city and it's completely unrelated

**Comment by GinTonic34** [comment]
> I don't use the minecraft launcher. It's just the dedicated server

I see. I dont have another PC so I cant double check  if what happens to me happens to everyone.

Out of couriosity: Whats happening to the cities (only answer that if its easy to explain :)

 Personally can live with the portal "workaround" of restarting my launcher for world generation (as thats a pretty rare event)

**Comment by polarbub** [comment]
What I do to generate structures is loop through all of the structures in the chunk and generate them only if they're end cites. This check was borked and wasn't picking up when there was one.

**Comment by polarbub** [comment]
> Personally can live with the portal "workaround" of restarting my launcher for world generation (as thats a pretty rare event)

I'll try your seed to see if that's the issue

**Comment by GinTonic34** [comment]
Dont bother, I have a feeling it might be smth with my PC.  If the end cities will generate again its already awesome.

**Comment by polarbub** [comment]
End cites should be fixed, can you test?

**Comment by GinTonic34** [comment]
For me End cities work again, awesome! Thx for fixing it :)
