### ISSUE TITLE
Support for 1.16.3

### ISSUE THREAD

**Issue by God-ly** [DeadlyMC/ProtoSky#6]
Will there be support for 1.16.3? This is the last update for 1.16 so there will be many months before a new update happens.

**Comment by aqnox** [comment]
Hi, I added support for 1.16.4 in #7

**Comment by God-ly** [comment]
Thanks!

**Comment by God-ly** [comment]
@aqnox i can't find the place to download the 1.16.4 jar, how do I do it? Or, in other words, is it enough to just make the changes on the branch and insert the mod into the mods folder as a zip file?

**Comment by aqnox** [comment]
I made a release compiling the recent pull requests: https://github.com/aqnox/ProtoSky/releases/tag/v1.1.1

**Comment by polarbub** [comment]
The 1.16.2 version works for 1.16.3.
